services:
  api:
    extends:
      file: docker-compose.base.yml
      service: base-api
    image: xtrime/telegram-api-server:dev
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - ./dev/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    ports:
      - "127.0.0.1:9503:9503"
      - "9003"
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
    command:
      - "-s=session"
  mysql:
    extends:
      file: docker-compose.base.yml
      service: base-mysql
    ports:
      - "127.0.0.1:9507:3306"
networks:
  default:
    name: telegram-api-server