FROM xtrime/telegram-api-server:latest

ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/

RUN chmod +x /usr/local/bin/install-php-extensions && \
    install-php-extensions xdebug && \
    rm /usr/local/bin/install-php-extensions && \
    echo "" >> "$PHP_INI_DIR/conf.d/xdebug.ini" && \
    echo "zend_extension=xdebug.so" >> "$PHP_INI_DIR/conf.d/xdebug.ini"

ADD docker/php/conf.d/. "$PHP_INI_DIR/conf.d/"

EXPOSE 9503
EXPOSE 9003

ENTRYPOINT ["./entrypoint.sh"]
